### ISSUE TITLE
Support for Axis Bank statements

### ISSUE THREAD

**Issue by Just5KY** [assetgrid/assetgridapp#36]
Our goal is for Assetgrid's CSV importer to be flexible enough to import any CSV file, but we know that some banks aren't exactly keen on following standards.

**Describe the issue**
What is the problem when importing the CSV file?
- Fields are missing
- Extra fields that are not required (can be manually removed before uploading for import)

**Describe what is needed to resolve the issue**
What do you think it would take to be able to import the CSV file. How can it be integrated into the existing process?
-  The bank has Credit and Debit column, and a description column that has payment method and sender/recipient.
- The Date column has two different styles.
- There is no Unique ID column.

**Upload a sample**
Please attach a sample CSV file that illustrates the issue. You can open CSV files in Excel and remove rows or sensitive information.
- [sample satement.csv](https://github.com/assetgrid/assetgridapp/files/9780025/sample.satement.csv)
  - DR = Debit amount
  - CR = Credit amount
  -  BAL = Balance amount

**Comment by alex6480** [comment]
This is exactly why I created this issue template. That CSV file is a good challenge.

1. **Credit/debit column**: I'll add an option to add amount with two columns instead of one. That'll probably be useful for other people.
2. **Description column has sender/receipient** I believe this can be solved with the regex feature that currently exists. It's a bit advanced, but I don't think it can be made any easier.
3. **Date has multiple formats** I can't see that in the CSV file. I can't think of any way to add support for multiple date formats that won't also turn the CSV import tool into a mess. I'm listening if you have any suggestions.
4. That's not an issue. If you select "auto" Assetgrid will generate a unique ID which should prevent duplicates in most cases.

I'll also add an option to skip the first N lines of the file. I think that could be useful.

Do you think that would be good enough for your use case?

**Comment by Just5KY** [comment]
Yes, I can work with regex and fix sender/recipient.
I can manually fix the date column before uploading the file to import.

**Comment by alex6480** [comment]
I've added the features to the newest version of Assetgrid.

In your case, skipping the first 9 lines, makes it correctly parse the content.
You can fix the dates using Regex. The following regex will capture the date parts no matter if a / or - was used to separate them.

    (\d+)[-/] (\d+)[-/] (\d+)

You can then recombine them using the pattern feature with your symbol of choice and use that to parse the dates. {1} means that it will output the value of capture group 1 in the regex.

    {1}/{2}/{3}

Similarly you can write a regex and then use a capture group to keep only the section of interest.
