### ISSUE TITLE
Issue with decimal places

### ISSUE THREAD

**Issue by SlawekJ-G** [assetgrid/assetgridapp#48]
Hi,
1st of all - even if the app is not yet fully usable in my case, I like very much its clean view and simplicity!
I have just installed Assetgrid in the container with MariaDB as DB engine.
I have noticed, that when I put any new (or edit, doesn't matter) transaction, I can't put numbers like 123,45. When I just type . or , character, value in the field is cleared to 0.
I am not sure if it is related, but in DB structure I can see amount value is bigint:
<img width="418" alt="image" src="https://user-images.githubusercontent.com/116116794/196531230-88723180-513a-4f29-9f20-42ecaf506778.png">
In Preferences I have changed decimal separator to ",", and thousands separator to ".". However, even if I rollback this to defaults, behavior is still the same.

Sławek

**Comment by alex6480** [comment]
It is not a database issue. Internally amounts are multiplied as integers to prevent floating point errors, but you can enter values with up to four decimal places.

The number input is a bit finicky, the issue is that if you enter something that cannot be parsed as a number, it clears to 0. The preferences are only for the display of numbers. The number input is in your browser language, so you need to use the decimal separator associated with that.

What browser do you use and which language is it configured in?

**Comment by alex6480** [comment]
What happens if you write the number without commas first and then add the comma in the middle of the number?

I will try to fix the number input for the next release, but I am pretty sure it's possible for you to enter decimal numbers. The question is how.

**Comment by SlawekJ-G** [comment]
🤦‍♂️
so - when I first put whole amount and then put decimal separator in between - it works 🤣
So it is only not working when I type and try to write like 12,34 in in single step.
Thanks for this workaround 👍

**Comment by alex6480** [comment]
I've made some changes to the number input on the development branch.
Do you mind giving it a try?

It's assetgrid/assetgrid:develop on docker

**Comment by SlawekJ-G** [comment]
Thanks @alex6480 ! now works as expected 😊

**Comment by alex6480** [comment]
Great. Thanks for testing it 🙂

Please switch back to the :latest tag or a version tag. The development branch is not stable and future development builds may corrupt your database.

The current development branch did nok make any database changes, which is why it was fine to switch temporarily.

I'll push these changes to the stable branch in the near future.
